const EVENT_ACCOUNT_POSITION = "outboundAccountPosition"
const NUMBER_TICKERS = 10
const INTERVAL_TRADE_WS_CHECK = 5000
const INTERVAL_WS_LATENCY_CHECK = 60000

module.exports = { EVENT_ACCOUNT_POSITION, NUMBER_TICKERS, INTERVAL_TRADE_WS_CHECK, INTERVAL_WS_LATENCY_CHECK }